### ISSUE TITLE
[Request] Collapse library and note list to single column

### ISSUE THREAD

**Issue by anthonyajumelles** [kmwallio/ThiefMD#101]
Putting the library and note list in a single column would allow the app to function better on mobile/smaller screens as well as clearly separating between organization and writing function.

On bigger screens you end up with a lot of wasted space due to two columns which can be mainly empty.

See NewsFlash (https://gitlab.com/news-flash/news_flash_gtk) for an implementation.

**Comment by marek-lach** [comment]
> On bigger screens you end up with a lot of wasted space due to two columns which can be mainly empty.

Not true, if you have multiple larger projects you're writing, like a novel, a podcast etc., like I do, in various stages of development, that you want to keep track of.

> Putting the library and note list in a single column would allow the app to function better on mobile/smaller screens as well as clearly separating between organization and writing function.

That's how Ulysses has it organized for mobile too. It seems on mobile having sheets expand out of folders on a single screen column/screen would make sense:

![iPhone-Ulysses-800x711](https://user-images.githubusercontent.com/45913977/107531992-512ba700-6bb5-11eb-9d71-a4bf631897e3.jpg)

**Comment by kmwallio** [comment]
Thanks for the feedback.

Is the request for this just on low resolution devices, or the hope to have a preference that has single pane instead of dual pane for the library?

**Comment by kmwallio** [comment]
I've been playing around with this, but the issue I'm running into is the Hdy.Leaflet is a fixed size and doesn't allow for adjustment like the Gtk.Paned.

Still trying to read/lookup if there's a way to do have an adjustable Leaflet type widget. With the Hdy.Leaflet and sizing the panels, I'm not sure how to scale if the System Font size is larger, or if there's some math for recommended pane locations.

**Comment by kmwallio** [comment]
![Work in Progress](https://user-images.githubusercontent.com/132455/112354180-a9ac9480-8c89-11eb-9beb-c0b35035a84a.gif)
