### ISSUE TITLE
Shortcut for links

### ISSUE THREAD

**Issue by TheNomad11** [kmwallio/ThiefMD#102]
When blogging, you use lots of links to other websites. What about adding a shortcut `CTRL + L ` for example? It would be useful if the text that is used as link text gets displayed in a different color as the link itself. Currently both are displyed in the same color which makes reading hard. Thanks a lot for developing this app, it is about to become one of my favorites!!

**Comment by kmwallio** [comment]
Thanks for the feedback, I could see this being useful.

If we implement this, I'm thinking if there's no text selected, present a pop-up for text and a URL. If there is text selected, if it looks like a URL, insert \[cursor_here\]\(https://selected-url.ext\) and if it's not a URL, put the cursor in the parentheses instead.

Does this fit what you had in mind, or is there a different workflow you'd prefer?

**Comment by TheNomad11** [comment]
Yes, that's exactly what I had in mind. That would be perfect. Thanks alot!

**Comment by kmwallio** [comment]
This is currently what I have prototyped. A lot of applications use `Ctrl+K` as the shortcut key, so I currently have it set to that for consistency.

Instead of showing a Pop-over, ThiefMD will insert the mark-up.  Pressing the `Tab` key will switch from the link text to the URL (and if you're at the end of some markup, it'll go out of the markup).

![Ctrl+K shortcut scenarios](https://user-images.githubusercontent.com/132455/109404666-0d5ad080-791d-11eb-9036-6c12743148bc.gif)

**Comment by TheNomad11** [comment]
Perfect, thanks a lot! I found many apps use `Ctrl+L` but actually it does not matter so much. L = link sounds more logical. Do you what K refers to?

**Comment by kmwallio** [comment]
I'm not 100% sure what K is supposed to refer to. I always remember it as linK or the k sound in anchor.

**Comment by TheNomad11** [comment]
Aha, ok, good idea, I try to remember it that way as well, then

**Comment by kmwallio** [comment]
> Currently both are displayed in the same color which makes reading hard.

@TheNomad11, we added an [Experimental Mode](https://github.com/kmwallio/ThiefMD/discussions/114) to help with readability around links and images. Images will always have the ![alt-desc] displayed, but links will just show their text. If the theme has links the same color as text, links will be displayed as [link text].

Let me know if this helps with the readability problem. If not, I'll try to think of something.
