### ISSUE TITLE
[Request / Suggestion]: Seperate Notepad pane

### ISSUE THREAD

**Issue by TheNomad11** [kmwallio/ThiefMD#106]
When writing, I oftes use lots of different sources, quotes etc that I prefer to put in a notes file. I have been searching a lot but have not found any usable Linux application with a seperate Notes pane. Scrivener has it of course - see here Document notes on the right side http://oceanofdmg.com/wp-content/uploads/2018/07/Scrivener-for-Mac-Offline-Installer-Download.jpg. Some kind of Split-screen functionality might be an option, too, so that I can open a specific note/file in a seperate pane as it is possible in some text editors: https://kate-editor.org/post/2019/2019-09-12-kate-in-the-windows-store/images/kate-on-windows-split-view.jpeg

**Comment by kmwallio** [comment]
I like this suggestion, but it's going to take some noodling on what to implement, and how to implement it. Feel free to share any thoughts or desires as well.

Depending on your use case and how quickly you want the feature, [novelWriter](https://novelwriter.io/) has in-file note and tagging support. [manuskript](https://github.com/olivierkes/manuskript) has note support similar to Scrivener.

### This is just a brain dump:

I like organizing my writing as:

![Manuscript breakdown in ThiefMD](https://user-images.githubusercontent.com/132455/109427556-bfd77580-79a7-11eb-8a19-501512362bd5.png)

In each chapter, I like to organize it into [scenes or beats](https://www.savannahgilbo.com/blog/plotting-save-the-cat). Personally, I'd like to have the Chapter notes (tied to the folder my file is in), and then Scene notes (tied to the Markdown file I'm editing). In addition to Scene notes, I'd want Labels and Tags.

For Chapter notes, we currently create a `.thiefsheets` file that stores metadata on export ordering, and files/folders to hide.

![.thiefsheets metadata file for organizing documents](https://user-images.githubusercontent.com/132455/109428186-c9161180-79aa-11eb-93cf-f1e6aa666703.png)

We could put scene notes here, but if the file gets corrupt, we lose all the notes. Moving sheets between folders introduces more complexity and moving parts.

I like the idea of creating a .notes file alongside the markdown file. So if I have `my-scene.md`, I'd have `my-scene.notes` that's a JSON file (the file only exists if there's notes, tags, or labels associated with the markdown file). If someone's moving files in their File Manager, it'll be a visual clue that the files are related, and it'll also let other apps potentially use the notes file. Additional files would create some visual clutter in the File Manager, but I think it helps prevent lock-in, corruption, and the need to have a separate database to manage.

***Competitive Analysis? :stuck_out_tongue_closed_eyes:*** [Ulysses supports tags/keywords at the end of the file](https://ulysses.app/kb/keywords-in-markdown-files) in a way that would be compatible with [Bear.app](https://blog.bear.app/2020/05/getting-started-with-using-and-organizing-tags-in-bear/). novelWriter uses novelWriter specific syntax in the file. There doesn't seem to be a set standard, but using a separate file would let you edit/export your work in [Apostrophe](https://somas.pages.gitlab.gnome.org/apostrophe/) or [Typora](https://typora.io/) without issue. I should probably document whatever is chosen so other apps can utilize it as well.

**Comment by kmwallio** [comment]
Just as an update, I created a [new branch for the next set of features coming to ThiefMD](https://github.com/kmwallio/ThiefMD/tree/ohtwo).

![Notes Prototype](https://user-images.githubusercontent.com/132455/111894430-ddf12e00-89c7-11eb-9588-03cb6129b57d.gif)
*Notes Prototype. There's a new header bar button for toggling the display of the Notes section. I plan on adding a field for Tags, and settings icon for changing the icon of the project/folder.*

One field is Notes tied to the file you're working on. For research it could be something like "Add Dr. So-and-So's paper to Literature Review", or if you're writing a novel something tied to a scene like "Make Larry's dialogue seem more natural. He currently feels robotic."

The other field is Notes tied to the folder. This could be chapter notes from your outline "Larry's all is lost moment when he discovers Monica thinks Eevee is cooler thank Pikachu", or if your Literature Review is in multiple files, and you want to make sure to include a reference to that paper...

Notes aren't included in the output, so I don't plan on adding spell check or syntax highlighting to them (if there's enough desire, I can add it).

I'm wondering if it'd be useful to have some warning badge on the Export Window if a Note has an `@TODO` or some other key phrase that could signal the draft isn't complete yet. This could create extra noise, but I'd be interested to hear any thoughts or wishes on how notes could tie in better to your workflows.

**Comment by TheNomad11** [comment]
Thanks so much for your work, this looks brilliant! Perfect! Happy to see both sheet and project notes!
