### ISSUE TITLE
Bold/italics, cursor position when resuming writing

### ISSUE THREAD

**Issue by davidbosman** [kmwallio/ThiefMD#120]
Select a word, put it in bold or in italic. It works as expected, fine. Now, with the text still being selected press the right arrow to resume writing: writing starts *inside* the bold/italic closing tag, aka the new text is in bold or in italic too. 

Shouldn't the cusor resume writing *outside* of the closing tag? Since I just made a selection to indicate what I wanted to put in bold or in italic, it is probable I do not want the following text to be impacted.

**Comment by kmwallio** [comment]
> Shouldn't the cursor resume writing outside of the closing tag?

I agree, more than 90% of the time, if I'm formatting selected text, I want my cursor out of the selection and formatting when I'm done.

I don't think I've seen this in other markdown editors, so there wasn't any feature to copy from :stuck_out_tongue_closed_eyes: 

I'll see if I can get this done.
