### ISSUE TITLE
Support for Citations

### ISSUE THREAD

**Issue by kmwallio** [kmwallio/ThiefMD#121]
[PanDoc support BibTeX Citations](https://pandoc.org/MANUAL.html#specifying-bibliographic-data)

Add support for detecting and reading Bib files. Editing can be done in plaintext for initial support.

**Comment by gunwald** [comment]
I think, this would be a killer feature, that would give us finally a great GTKish open source markdown writer ready for academic writing. I am looking out for such a tool for quite some time now.
At the moment I am stuck with an atom setup, here it works like this: 

You need to have a biblatex file and a citation style file (CSL). Than you can use the ID of the bib items in the biblatex file to cite in a markdown document. For example:

```
This is my text »and this is not«.[@somebody2017, 45] Here comes my text again,
but I want to give you some footnotes^[I really have to explain this to you, do I? 
Look here @metoo2016, p. 13 and here @qualunque2010, p. 5.]
```

Pandoc-citeproc would turn both into footnotes substituting all the references according to the given style.

ThiwMD could parse a biblatex file, that could be given by the config part at the beginning of a document:
---
title: "My Titel"
author:
  - Qualunque
affiliation: What ever
bibliography: ./bibliography.bib
biblio-style: ./Novanimus.csl
--- 
And autocomplete if you stat typing @.... If a proper bib item ID is completed it could show the proper parsed reference on mouse over.

**Comment by kmwallio** [comment]
Thank you for the suggestions and input! I was not aware of the CSL file and will make sure to be aware of that during implementation.

Assuming no major bugs in the latest release, I'm hoping to be heads down implementing this and [Project/Page Notes](https://github.com/kmwallio/ThiefMD/issues/106) for a 0.2.0 release.

> And autocomplete if you stat typing @....

We do plan on parsing the bib file. Autocomplete is new in [GtkSourceView5](https://gnome.pages.gitlab.gnome.org/gtksourceview/gtksourceview-5.0/index.html), so we might wait until we can migrate to that for autocomplete. This probably won't be until Ubuntu has a GTK4 library in the main packages and Gnome SDK 40 is available for flatpak.

The plan is to do [right-click for insertion](https://github.com/kmwallio/ThiefMD/issues/122) until we have a suitable autocomplete implementation.

**Comment by kmwallio** [comment]
Just as an update, this is what it currently looks like:

![Right-click to insert citations](https://user-images.githubusercontent.com/132455/112592974-14fa8180-8dc4-11eb-94c9-62206b347576.gif)

I'm working on detecting the version of pandoc available to use the appropriate command line.

**Comment by kmwallio** [comment]
@gunwald 

> And autocomplete if you stat typing @.... If a proper bib item ID is completed it could show the proper parsed reference on mouse over.

:sweat_smile: so I found [this tutorial on adding autocomplete](https://warroom.rsmus.com/do-that-auto-complete/). I'll be hiding it behind the Experimental Mode in the next release.

![Citation auto-complete](https://user-images.githubusercontent.com/132455/112737639-299c5e00-8f19-11eb-9a6a-591576f3f082.gif)

Just to clarify, was the ask for @citations to have a the formatted citation show up on mouse over? [Right now we extract the title](https://github.com/ThiefMD/BiBtex-vala), but I could have a tooltip showing most of the citation (it wouldn't match the CSL though).

If you have any additional suggestions or ideas, feel free to create a new issue.
