### ISSUE TITLE
App translation don't work

### ISSUE THREAD

**Issue by eson57** [kmwallio/ThiefMD#126]
Well, at least Swedish translation don't work.

Using: Flatpak
Desktop Environment: Cinnamon
OS: Linux Mint 20.1

**Comment by kmwallio** [comment]
Thanks for letting me know. I found the issue with loading the language files and checked in a fix. I'll try to setup a bugfix release within the week.

**Comment by kmwallio** [comment]
This should be fixed in the latest release. I needed to install `org.gnome.Platform.Locale//3.38` and restart my user session to see the change.

**Comment by eson57** [comment]
Thanks!  I'll start a new issue about missing translation strings.
