### ISSUE TITLE
Still stuck at 0.12 and 0.14

### ISSUE THREAD

**Issue by TheNomad11** [kmwallio/ThiefMD#129]
Thanks for many new releases and new features! Unfortunately, on Linux Mint I am still stuclk at 0.12 or 0.14 (Flatpack). Is there a way to use the newest release 0.18? When will they be available on Flatpack or in the Ubuntu repository? Thanks!

**Comment by kmwallio** [comment]
It should be on [flathub](https://flathub.org/apps/details/com.github.kmwallio.thiefmd). Flatpak checks for updates after reboots/logins. To manually update, you can do:

`flatpak update`

For Linux Mint using the Ubuntu PPA, we switched to using libhandy which is available on 20.10+ but is not on the LTS branch. It looks like Linux Mint uses 20.04 as a base.

You can do `sudo apt uninstall com.github.kmwallio.thiefmd` and switch to the flatpak release to stay current.

This will not clean up `~/.local/share/ThiefMD` and settings will be lost. It is safe to remove this directory, but you may want to copy `~/.local/share/ThiefMD/styles` and `~/.local/share/ThiefMD/css` if you don't want to redownload any themes.

**Comment by TheNomad11** [comment]
Oh, thanks so much. Something must have been wrong with my flatpak installation. `flatpak update` gave me 60 updates. Now I have 0.1.8. Thanks so much!

**Comment by kmwallio** [comment]
No problem!
