### ISSUE TITLE
Icons, buttons and alignment inconsistency 

### ISSUE THREAD

**Issue by environmentalcode** [kmwallio/ThiefMD#148]
![Screenshot from 2021-04-28 16-57-11](https://user-images.githubusercontent.com/65958239/116428245-0977fb80-a845-11eb-955e-4298d7a1fe3e.png)

Apps (they are all unfocused) from top to bottom are: ThiefMD, Apostrophe, Marker, Quilter.
As you can see from the screenshot, other markdown apps follow the same icon theme so they look consistent between them and the general user's theme. 
1) Why doesn't that happen in ThiefMD? It looks like it uses it's own icon theme or something like that.
2) What's the matter with that "New Sheet" icon button that looks so out of place and misaligned?

**Comment by kmwallio** [comment]
> Why doesn't that happen in ThiefMD? It looks like it uses it's own icon theme or something like that.

We request the flat icon theme from the system. I can change that to make it fit in.

> What's the matter with that "New Sheet" icon button that looks so out of place and misaligned?

The goal was to make it align with the sheet's pane.

**Comment by environmentalcode** [comment]
> We request the flat icon theme from the system. I can change that to make it fit in.
 
Thank you, that would be great!

> The goal was to make it align with the sheet's pane.

Ok, I understand and it actually makes sense. But still it is not aligned with the sheet's pane as you can see from the following the screenshot. 

![Screenshot from 2021-05-03 09-49-58](https://user-images.githubusercontent.com/65958239/116852663-04280180-abf5-11eb-9bfa-09e2ebbc62ec.png)

**Comment by kmwallio** [comment]
I believe this should be fixed in the 0.2.4 update.
