### ISSUE TITLE
Discontinue suffix'd releases for tags

### ISSUE THREAD

**Issue by jonringer** [kmwallio/ThiefMD#162]
A lot of packaging software works on upstreams adhering to a convention for tags. Each tag with a unique suffix really makes it hard to determine if there's a new release automatically, and then requires some manual intervention.

I'm not against codenames, just please don't put them in the actual tag (e.g. `v0.2.5-stability` -> `v0.2.5`)

Example confusion: https://github.com/NixOS/nixpkgs/pull/172024

**Comment by kmwallio** [comment]
Thanks for letting me know. I'll stop the suffix in the next release
