### ISSUE TITLE
Update flatpak environment

### ISSUE THREAD

**Issue by LukaszH77** [kmwallio/ThiefMD#175]
ThiefMD flatpak uses an unsupported Gnome runtime:

```
Info: runtime org.gnome.Platform branch 41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.kmwallio.thiefmd
```

Is there a chance for an update using more recent runtime?

**Comment by kmwallio** [comment]
There is. I need to change the spellcheck library and a few other things. So I'm currently refactoring some code to make it easier to do in the future if needed.

**Comment by LukaszH77** [comment]
Thank you!

**Comment by qwertychouskie** [comment]
I was just doing some "spring cleaning" of my system today, and also noticed the issue.  Good to see it's in progress.

**Comment by kmwallio** [comment]
New version should be on Gnome SDK 44!

**Comment by LukaszH77** [comment]
Thank you!
