### ISSUE TITLE
Please dont hardcode a theme

### ISSUE THREAD

**Issue by Alexmitter** [kmwallio/ThiefMD#44]
Please don't do that. It breaks everything.
![image](https://user-images.githubusercontent.com/6940479/93861851-792b7400-fcc1-11ea-8631-ba2cdb0209e3.png)

**Comment by kmwallio** [comment]
I'll look into using the user's current theme, then having some options in the preferences.

**Comment by kmwallio** [comment]
In [the next release](https://github.com/kmwallio/ThiefMD/commit/a5f29161ba530d6bf425374a360cdbb1616319ea), choosing "Match UI to Editor Theme" will attempt to change the window decoration.  Unchecking it will use the user's Gtk Theme.

It'll try asking for light/dark mode of the user's theme depending on the editor theme selected still.

![image](https://user-images.githubusercontent.com/132455/94090857-8e8cc500-fdcb-11ea-9f5e-16eb0f70d7d4.png)

**Comment by Alexmitter** [comment]
Thank you, this is a good solution.
It is always preferable to give the user the choice to define themselves how the apps they are using should look like, even if it might be unattractive looking to us developing them.

**Comment by kmwallio** [comment]
Thanks a lot for the feedback.  This should also make sure user's using themes focused on accessibility are still able to use the app :smile: 

I'll close this issue, and if things look stable, hopefully it'll be available for everyone sometime this weekend or early next week.
