### ISSUE TITLE
Customizable fonts?

### ISSUE THREAD

**Issue by jennraeross** [kmwallio/ThiefMD#69]
Are there currently plans to add the ability to customize font-size and font-family?

**Comment by kmwallio** [comment]
It's not on my current list of items to tackle, but would be a good option to have in the future.

In my mind there would a drop down list of Selected/Preferred Fonts, and then a drop-down of Font Sizes, then possibly a gear/settings icon to bring up the OS Font Chooser of all install fonts and size options.

The default preferred fonts would be the current [iA Writer Duospace](https://ia.net/topics/in-search-of-the-perfect-writing-font), a Serif Monospace font probably [Courier Prime](https://quoteunquoteapps.com/courierprime), then the Default OS font.

Does this sound ideal for you?

**Comment by kmwallio** [comment]
I have an initial prototype in the font-selection branch. ThiefMD with [Redacted Script](https://github.com/christiannaths/redacted-font) for fun.

![image](https://user-images.githubusercontent.com/132455/95696718-173f9980-0bf1-11eb-9518-f39b10b05b54.png)

The setting will appear in the next release in the Display preferences.

![image](https://user-images.githubusercontent.com/132455/95696797-6f769b80-0bf1-11eb-8914-41b35c5ce69c.png)

Feel free to let me know if you have any other suggestions/asks!

**Comment by jennraeross** [comment]
Oh my goodness, you're fast #^-^;#

When I'd put those two items up, I'd just thought they'd be nice to put on the backburner, maybe brought out at some point in the future, but you tackled both of them before I even got another break at work. I guess that explains why this app has improved so drastically since it released #^-^# Thank You!
