### ISSUE TITLE
Selectable elements stretched in export preferences tab

### ISSUE THREAD

**Issue by anthonyajumelles** [kmwallio/ThiefMD#77]
Here you can see the elements displaying properly in the editor preferences tab:
![Screenshot from 2020-10-17 18-07-03](https://user-images.githubusercontent.com/62868183/96354386-15b81a80-10a4-11eb-8e9d-1a710f6bdc3b.png)

Here are the export preferences elements stretched at various window widths:
![Screenshot from 2020-10-17 18-07-08](https://user-images.githubusercontent.com/62868183/96354401-341e1600-10a4-11eb-87bd-c3f967b75f8d.png)
![Screenshot from 2020-10-17 18-07-00](https://user-images.githubusercontent.com/62868183/96354402-34b6ac80-10a4-11eb-9a47-0337badedd9d.png)

**Comment by kmwallio** [comment]
Thanks for reporting the issue.

The stretch is due to the margin entries. I think I might move them below the page size selection so the switches can align and not stretch, and then the label alignments for the margin will be off, but not look too out of place.

**Comment by kmwallio** [comment]
I've updated the order of the elements, and put the margin selectors in a separate grid (this is currently in the beta branch 832df7b49beb32b86be50a847b6a4cbb2a528628 ).

I think it looks a lot cleaner now. Thank you for reaching out about the issue, and if you have any additional suggestions, I'll be glad to hear them!

![Non-stretched switches in preferences](https://user-images.githubusercontent.com/132455/96376778-c6bac580-1135-11eb-91fa-2171494f2bd7.png)

**Comment by anthonyajumelles** [comment]
Looks solid! Thank you very much.
