### ISSUE TITLE
Write.as (write freely) as an Export Target

### ISSUE THREAD

**Issue by kmwallio** [kmwallio/ThiefMD#80]
User's should be able to publish to a [WriteFreely](https://writefreely.org/) hosted blog through the export window.

Plans:
* Allow for authentication through preferences.
* Only show export/import options if user is logged in, or if they check a box for anonymous writefreely support.
* Store metadata in YAML frontmatter
* Parse YAML frontmatter and strip from contents on publish

[Client Library in separate repo](https://github.com/ThiefMD/writeas-vala)

**Comment by kmwallio** [comment]
![writeas-publisher](https://user-images.githubusercontent.com/132455/96683706-5c6d7500-132f-11eb-82f0-0790ca72d6d4.png)

Working on figuring out libsecret, and then releasing this to the wild.

**Comment by kmwallio** [comment]
Current work is in `export-revamp` branch if you want to try/follow along. It'll require re-initing and resyncing the git submodules.

**Comment by kmwallio** [comment]
Currently in the `beta` branch ready for the next release

**Comment by dejalavidavolar** [comment]
THANKS YOU SO MUCH FOR THIS!!!
