### ISSUE TITLE
Crash on adding Ghost blog

### ISSUE THREAD

**Issue by Brutus11111** [kmwallio/ThiefMD#89]
When I go to the menu, then preferences, then connections, select ghost, I can type in my credentials. When I select the "Add Account" button, ThiefMD crashes. 

Log file:

http://termbin.com/rgjk

**Comment by kmwallio** [comment]
Can you share what Linux distro you're running and how you installed ThiefMD (flatpak/AUR/deb/rpm)?

**Comment by Brutus11111** [comment]
I installed this on Manjaro through the AUR

-------- Original Message --------

**Comment by kmwallio** [comment]
Thanks, I'll start investigating!

**Comment by kmwallio** [comment]
@Brutus11111, What desktop environment are you using?

**Comment by Brutus11111** [comment]
> @Brutus11111, What desktop environment are you using?

Technically none, I'm using the i3 window manager.

Video: 

https://streamable.com/q6jqhd

**Comment by Brutus11111** [comment]
> Thanks for reporting this. It looks like if we're unable to open a successful connection to the provided URL we crash.
> 
> I'll start work on checking for network connectivity before attempting a connection, and then see how to gracefully handle when the URL is invalid or a connection cannot be established. Along with adding/validating https/http at the start of a URL.
> 
> If you enter the full `https://ghost-blog.com` to a valid ghost install, does the connection for for you?

Sorry for not replying. 

I was testing this earlier with what I assumed was a valid URL. Now when I do have the correct URL it does work as it should.

I assumed it was https://blogname/ghost . For the sceen recording i did enter garbage.

Status:
Incorrect URL: Crash
Correct URL: Works fine

**Comment by kmwallio** [comment]
> I assumed it was https://blogname/ghost 

Thanks for letting me know. I'll add a check for trailing /ghost as well.

**Comment by kmwallio** [comment]
The crash is fixed by [317bd0d9e](https://github.com/ThiefMD/ghost-vala/commit/317bd0d9e1d45766f000488f4aad868c23b3c941) and [03bb950617](https://github.com/ThiefMD/ghost-vala/commit/82dc9024fbf7c13088459dc329bd69).

I'll see if I can update the UI to provide better feedback and error messaging.

It won't be available until the next release.
