### ISSUE TITLE
how to localise?

### ISSUE THREAD

**Issue by n1trux** [kmwallio/ThiefMD#90]
can you please create documentation on how to localise the UI?

I really like GNU gettext as a system to translate stuff because it already has lots of tooling available, even online editors. Would be cool if Thief supported that.

**Comment by kmwallio** [comment]
Thanks for reaching out about this. I'll setup some documentation and get the files setup.

**Comment by kmwallio** [comment]
I created the pot template file and started a [project on POEditor](https://poeditor.com/join/project?hash=iQkE5oTIOV).

Feel free to let me know if I'm missing anything.
