### ISSUE TITLE
Add ability to adjust line spacing

### ISSUE THREAD

**Issue by kmwallio** [kmwallio/ThiefMD#94]
Improve readability and accessibility.

**Comment by davidbosman** [comment]
Hi, that'd be neat (BTW, it was I  that requested it on your reddit post a few days back ;)).

**Comment by kmwallio** [comment]
Thanks for coming over to Github to commend, and thanks for the additional feedback!

There are a lot of features that could make the application more accessible for more users, but they're scenarios I wouldn't think of unless someone voiced them.

So thank you very much for taking time to try the app and providing beneficial feedback.

**Comment by kmwallio** [comment]
Just as an update, working on this. Planning on allowing choices from 1.0 to 3.5.

![image](https://user-images.githubusercontent.com/132455/107130284-b06d7c80-6880-11eb-9419-9312cdfacbe8.png)

![image](https://user-images.githubusercontent.com/132455/107130293-b9f6e480-6880-11eb-8060-93c15713534b.png)

![image](https://user-images.githubusercontent.com/132455/107130299-c4b17980-6880-11eb-9dbb-0e78ea96a1fe.png)

**Comment by davidbosman** [comment]
great :)
