### ISSUE TITLE
Suggestion: Customize info displayed in the sheets side panel?

### ISSUE THREAD

**Issue by davidbosman** [kmwallio/ThiefMD#96]
When you have multiple sheets in a directory/project *and* if those sheets don't all use a Markdown title tag as their first line (titles appears in bold in the preview), it can be hard to quickly see where the preview of one sheet ends and where the preview of the next one begins.

Have you considered adding some visual clue to mark the separation between sheets? What I can think of:
* Make every 1st line in the preview bold, no matter if it's a title or not?
* Add somepadding space between around previews?
* Add a thin separating line?
* Alternate background color every odd line? Nothing too contrasted but that shows there is a break between two previews?
* Or maybe have an icon next to the first line of each sheet? But that would add noise to the UI (I like how clean and minimalist it is ;)).

Also, the preview is cool to have, but it can also be useful to be able to hide it, ie in a project with *many* sheets where one may prefer to see more sheets title than their previews, without having to scroll down. Is that an option you would consider adding? Something like a "Show/hide preview", or even an option to set the number of lines in the preview?

Thx, & thx again (from an ex-Ulysses longtime user) for ThiefMD. I just started using it a few days ago but it feels *great* (drafting my next book in it) ;)

**Comment by kmwallio** [comment]
Sorry for not replying yet. Still trying to think this through. I do agree the default visual has some accessibility issues:

![Default Sheets View](https://user-images.githubusercontent.com/132455/109857676-cbc57080-7c0f-11eb-9f93-6bfc8a57566e.png)

Line separation is available if you toggle "Apply Theme to Interface" in the preferences, but depending on the GTK theme used, it can cause some accessibility issues.

![Theme applied to Sheets View](https://user-images.githubusercontent.com/132455/109857799-eb5c9900-7c0f-11eb-861f-edd9163b8fb5.png)

I'm still experimenting with options, but for now I can add a button for "Always show border"

![Always show Sheets Border](https://user-images.githubusercontent.com/132455/109860788-6a070580-7c13-11eb-994c-f411c759edb2.png)

and use the default OS theme for showing the border.

I'm thinking of adding Always Show File Name / Disable Preview (only show titles), and figuring out font settings based on the font size for the editor.

Some long term goals are for managed projects where filename is hidden/not a concern, so I'm not sure if "Always show file name" will cause future confusion.

**Comment by kmwallio** [comment]
@davidbosman, is this visible enough?

![Light Theme with Gtk.Separator](https://user-images.githubusercontent.com/132455/110219600-2b708580-7e75-11eb-8efb-d218878d0d09.png)

This is the default Gtk.Separator, on a Dark Theme, it's almost invisible.

![Dark Theme with Gtk.Separator](https://user-images.githubusercontent.com/132455/110219625-417e4600-7e75-11eb-9971-3b56cd60a5f6.png)

**Comment by davidbosman** [comment]
@kmwallio I can only talk about the dark one 'cause I just can't see stuff over a light background: the line is not visible to me. I guess adding some bottom/top padding between each sheet could help then? Or if it is at all possible, have an alternate background shade from one to the other?

**Comment by kmwallio** [comment]
@davidbosman, I figured out how to grab the font color for the border :smile: .  I'm hoping to have the border always enabled. Please let me know if the border opacity is dark enough to see it. I have it set to blend with the background color, so I can make it pop more if needed.

![Dark Theme](https://user-images.githubusercontent.com/132455/110889199-93becd00-82a2-11eb-8eac-e05b70e12648.png)

![Light Theme](https://user-images.githubusercontent.com/132455/110889269-acc77e00-82a2-11eb-8340-4ddce41a1931.png)

**Comment by davidbosman** [comment]
Looks really fine to me. I don't think most users would fancy a more contrasted color for that border (making it too visible)?

**Comment by kmwallio** [comment]
> Looks really fine to me.

Thanks for letting me know!

> I don't think most users would fancy a more contrasted color for that border (making it too visible)?

I think most users want the borders to match their GTK Theme's colors. I don't want to provide too many customization options, but if it improves accessibility, I can look into allowing the user to choose a border color (or change the intensity).

**Comment by kmwallio** [comment]
Borders have been published in the latest release.

> Something like a "Show/hide preview", or even an option to set the number of lines in the preview?

I think I can add a drop-down somewhere for "No Preview / 1 Line / ... / 10 Lines"

**Comment by davidbosman** [comment]
Waiting for the AUR to be updated to get my hands on it (yep, I am that lazzy :p)
